# Generated by Django 5.1.1 on 2024-10-01 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                ("First_name", models.CharField(max_length=255)),
                (
                    "Middle_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("Last_name", models.CharField(max_length=255)),
                ("Title", models.CharField(max_length=5)),
                ("Fathers_name", models.CharField(max_length=255)),
                ("Mothers_name", models.CharField(max_length=255)),
                (
                    "Spouse_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Mobile_number1",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("Mobile_number2", models.BigIntegerField(blank=True, null=True)),
                ("Date_of_birth", models.DateField()),
                ("Gender", models.CharField(max_length=255)),
                ("Blood_group", models.CharField(max_length=3)),
                ("Email_id", models.EmailField(max_length=150)),
                ("Door_number", models.CharField(max_length=250)),
                ("Street_name", models.CharField(max_length=250)),
                ("Area", models.CharField(max_length=250)),
                ("District", models.CharField(max_length=250)),
                ("City", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=250)),
                ("Country", models.CharField(max_length=250)),
                ("pin_code", models.IntegerField(null=True)),
                ("Highest_Qualification", models.CharField(max_length=100)),
                ("Institute", models.CharField(max_length=100)),
                ("Stream", models.CharField(max_length=100)),
                ("Passed_out_year", models.IntegerField()),
                ("skills", models.CharField(max_length=250)),
                ("Job_category", models.CharField(max_length=250)),
                ("Company_Name", models.CharField(max_length=250)),
                ("Company_Current_location", models.CharField(max_length=250)),
                ("Job_Position", models.CharField(max_length=250)),
                ("Annual_income", models.CharField(max_length=1000)),
                ("published_date", models.DateField(auto_now=True)),
            ],
            options={
                "db_table": "new_detail",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_id", models.CharField(max_length=10, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "profile",
            },
        ),
    ]
